[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "tradingbot"
version = "0.0.0"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["TradingBot/src"]